### PR TITLE
use filter instead of images

### LINKED ISSUE #26: Load Time
The load time for all of the images for the website is awful. Took at like 3 minutes to load all the carousel images. The Meet the team pictures took like 1 min to load. Then you have to hover over all of them to load their black and white version. Perhaps add a loading screen overlay as the images load?

### PR DESCRIPTION
**Pull request by mahirk**
Updates team images to use filter instead of other images. Closes #26

### CODE REVIEW

**Comment by cedric2018** [comment]
Name and position aren't vertically centered. See Image:

screen shot 2016-08-14 at 1 23 29 pm

**Comment by cedric2018** [comment]
Filter isn't supported by Firefox :(

**Comment by mahirk** [comment]
@cedric2018 https://developer.mozilla.org/en-US/docs/Web/CSS/filter#Browser_compatibility

**Comment by mahirk** [comment]
@cedric2018 you want to test that on the phone with safari please and show me a screenshot, it looks different on the phone for me

**Comment by mahirk** [comment]
@cedric2018 any updates. @SkylerKidd can you have a look as well pls.

**Comment by cedric2018** [comment]
@mahirk the text/b&w hover effect doesn't even activate when I tap on the pictures on mobile in Safari :\

**Comment by mahirk** [comment]
Thats just weird, that shouldn't be a thing, its all HTML and CSS @ayush29feb can you have a look. If we want this change we need it quick!

**Pull request closed without merging**
