### PR TITLE
update to use font-awesome

### PR DESCRIPTION
**Pull request by mahirk**
Update for header images to use font awesome

### CODE REVIEW

**Comment by cedric2018** [comment]
Need to change the footer logos to font awesome too.

**Comment by mahirk** [comment]
@cedric2018 guess the interaction works, I forgot that was done

**Comment by mahirk** [comment]
@SkylerKidd can you have a look at this branch as well

**Comment by mahirk** [comment]
and now its conflicting...

**Comment by ayush29feb** [comment]
@mahirk it was conflicting with the navbar changes I made. Can you take another look if it's all good?

**Comment by ayush29feb** [comment]
If its good, go ahead and merge it,

**Pull request merged**
